name: Deploy to Neocities

# only run on changes to main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Set up any tools and build steps here
    - uses: actions/checkout@v1

    - name: Use Node.js
      uses: actions/setup-node@v2.1.4
      with:
        node-version: 12
    # When the dist_dir is ready, deploy it to neocities
    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v1
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: false
        dist_dir: public